### ISSUE TITLE
App Crash after update to 3.0.0-beta.3

### ISSUE THREAD

**Issue by mrwrighty** [triniwiz/nativescript-videorecorder#59]
### Which platform(s) does your issue occur on?
- iOS
- iOS 10.3.3

### Please, provide the following version numbers that your issue occurs with:
 Nativescript 5.2.3

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

### Is there any code involved? 
 3.0.0-Beta.3

advanced-video-view.js:199 TypeError: ex.getMessage is not a function. (In 'ex.getMessage()', 'ex.getMessage' is undefined)

No error occurs on iOS 12.1.4

**Comment by mrwrighty** [comment]
I have downgraded back to 3.0.0-beta.2 and the problem has gone away on iOS 10.3.3

**Comment by mrwrighty** [comment]
Hi, any update on this please. My app is no longer functioning because of this error 'ex.getMessage' is undefined. I have tried editing the code in the plugin, but have not been able to fix the issue.

plugin is still OK on iOS 12.2.4 but crashes on iOS 10.3.3

**Comment by mrwrighty** [comment]
Still getting this error, very frustrating. Have you given up supporting this product.

JavaScript error:
file:///app/tns_modules/nativescript-videorecorder/advanced/advanced-video-view.js:198:43: JS ERROR TypeError: ex.getMessage is not a function. (In 'ex.getMessage()', 'ex.getMessage' is undefined)
